name: Build and Release

on:
  push:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Create ZIP archive
        run: |
          mkdir output
          cd module
          zip -r ../output/RMX3231-Props-${{ github.ref_name }}.zip ./*

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: output/RMX3231-Props-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}